### ISSUE TITLE
Container watcher does not start

### ISSUE THREAD

**Issue by LucileDT** [wexample/scripts#13]
### Configuration
Title | Your information
------------ | -------------
**System** | Ubuntu 16.04 LTS
**`wex` version** | `master`

### Scenario
- Go to a Wexample website using a terminal and doing `cd <path of project>`
- Launch the website by doing `wex site/start`

### Expected behaviour
- All containers are launched and works

### Current behaviour
- The `watcher` container is not running

*Notes:*
After investigations, it seems that the container tries to start but dies after an error:
`gulp not found`

**Comment by weeger** [comment]
Solved the issue inside the last version on the watcher image, but a problem still persist : I'm not sur that wex scripts will take this latest image rather than the old one. Its due tu to the bad sychronisation between wex relases (tagging) and images auto rebuilding.

Next fixes here : https://github.com/wexample/scripts/issues/14
